### ISSUE TITLE
error running ffprobe [] exit status 1

### ISSUE THREAD

**Issue by dorianneto** [vansante/go-ffprobe#52] opened 2024-09-10 04:07 UTC
Hi,

I'm having an issue in production when running `ffprobe.ProbeURL()`. The app is dockerized and I can run ffmpeg/ffprobe via CLI normally.

I appreciate any ideas!

**Comment by dorianneto** [comment] 2024-09-10 19:21
I tried different inputs and it worked smoothly, but this image in specific is causing the issue: https://w7.pngwing.com/pngs/565/999/png-transparent-african-american-graphy-thought-thinking-man-miscellaneous-photography-people.png

**Comment by vansante** [comment] 2024-09-19 09:56
Can you be a little bit more specific? Do you have some sample code? What error/output are you getting?
Can you run ffprobe manually from the command line on the file and what do you get as output then?

**Comment by vansante** [comment] 2024-11-04 14:07
Closing for now, let me know if the problem persists.

**Closed as completed by vansante** 2024-11-04 14:07 UTC

**Comment by duckbrain** [comment] 2025-12-19 22:24
I got this same error because a filename was being corrupted (by my code) before it was passed to `ffprobe.ProbeURL`. I added the `-loglevel error` to override the log level to include the error message as well as `--` to ensure a filename starting with `-` couldn't conflict. That updated the error message to include the filename ffprobe received as well as `No such file or directory`.

```go
	res, err := ffprobe.ProbeURL(ctx, filename, "-loglevel", "error", "--")
```

**Comment by vansante** [comment] 2025-12-20 08:37
The error `No such file or directory` suggests the path to your file is incorrect.

**Comment by duckbrain** [comment] 2025-12-20 13:38
Yep, I got that. It only shows the error message if you add the additional arguments to send the error message to stdout. Since it took a while to figure that out (I didn't notice the wrapper function in my app was altering the filename, so I was shelling into the remote container and trying to reproduce with the filename passed to the wrapper), I was leaving that comment to help whomever else comes across this thread.

It seems to me that error should be the default log level, since the error message go-ffprobe returns is near-useless otherwise, but I imagine there's a reason fatal is used.
